### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by sebastienvermeille** [sebastienvermeille/another-protobuf-maven-plugin#27]
Perform a release of version 2.1.0 including the changes of this external contribution https://github.com/sebastienvermeille/another-protobuf-maven-plugin/pull/20

**Comment by sebastienvermeille** [comment]
I will deploy it manually as at this stage the CI is not yet ready for that.

**Comment by sebastienvermeille** [comment]
```
<dependency>
  <groupId>dev.cookiecode</groupId>
  <artifactId>another-protobuf-maven-plugin</artifactId>
  <version>2.1.0</version>
</dependency>
```

**Comment by S1artie** [comment]
Seems like something went wrong with this release; at least there is no sign of the plugin on maven central: https://central.sonatype.com/search?q=another-protobuf-maven-plugin
