### ISSUE TITLE
Sorting of proto files features should be documented

### ISSUE THREAD

**Issue by sebastienvermeille** [sebastienvermeille/another-protobuf-maven-plugin#30]
Document usage of the recently merged feature: https://github.com/sebastienvermeille/another-protobuf-maven-plugin/pull/20
in the maven site deployed on gh-pages

**Comment by S1artie** [comment]
There seems to already be some documentation found in the maven site: https://sebastienvermeille.github.io/another-protobuf-maven-plugin/compile-mojo.html#sortProtoFiles

Should I add some more detailed documentation, maybe an example of the ordering scheme?

**Comment by sebastienvermeille** [comment]
Hey @S1artie thank you for the proposal indeed I was thinking about an example of usage with ideally the output expected with some files.

Btw: really sorry it is still not available on sonatype no idea what is happening i wait for an answer from their support.
