### ISSUE TITLE
release 2.1.0 not available on Sonatype ?

### ISSUE THREAD

**Issue by sebastienvermeille** [sebastienvermeille/another-protobuf-maven-plugin#31]
For some reason the logs seems to be good but the release is not available on sonatype mirror servers.

I contacted the support and we are now following the new release 2.1.1 as they have already purged the 2.1.0 automatically. (Seems to be blocked in the staging area for some reason).

Let see

**Comment by sebastienvermeille** [comment]
Okay mea culpa it was my mistake.

Note for myself:
In order to be able to click on the **release** button  first I have to click on **close** button (this UX is totally counter intuitive to me)


Binaries are available here: https://s01.oss.sonatype.org/content/repositories/releases/dev/cookiecode/another-protobuf-maven-plugin/2.1.0/

So in a few hours/days should be finally discoverable via the search https://central.sonatype.com/search?q=dev.cookiecode

:crossed_fingers:

**Comment by sebastienvermeille** [comment]
It is there https://central.sonatype.com/artifact/dev.cookiecode/another-protobuf-maven-plugin

**Comment by S1artie** [comment]
Thanks a lot!
